### ISSUE TITLE
Only sets primary screen's background on multiple monitors

### ISSUE THREAD

**Issue by llimllib** [ungoldman/himawari-bg#2]
steps to reproduce:
- run himawari-bg
- see that only the primary screen's bg has been updated

**Comment by llimllib** [comment]
Looking at the code a bit, this is due to: https://github.com/sindresorhus/osx-wallpaper/issues/2

Love the idea, but only setting one monitor makes this not really too useful to me! Super neat work though, I don't mean to demean it at all.

**Comment by ngoldman** [comment]
Hi @llimllib! Thanks for the feedback. Would you expect it to set the background for all screens to the same image?

**Comment by jakiestfu** [comment]
I would like to see an option to specify monitors. Obviously that isn't as simple as it sounds but that'd be the idea, eh?

**Comment by llimllib** [comment]
Simplest would be a `-a` option to set for all monitors or something, that would probably do the trick for me.

**Comment by ungoldman** [comment]
Hello 👋 

It's been... _six years_... but this issue is now resolved!

`v2.0.0` release includes two new options for managing how the wallpaper: `screen` and `scale`.

With the `screen` option, you can select which screen `himawari-bg` updates.

The options are `all`, `main`, or a numeric screen index.

Example:

```
himawari-bg --screen=all
```

Full usage info is available in the [docs](https://github.com/ungoldman/himawari-bg#usage) or via `--help`.

**Note that these options are for macOS only.** I'm just exposing the options from the underlying library used for managing the wallpaper ([sindresorhus/wallpaper](https://github.com/sindresorhus/wallpaper)).

**Comment by llimllib** [comment]
🎉 thanks! I haven't used this in a minute, maybe I'll give it another go
